languageCode = 'zh-CN'
title = 'AI AGENT CRONJOB FOR WEB SEARCH BLOG'

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "长期追踪你想要了解的领域"
  author = "Cron Search Task"
  github = "https://github.com/EmptyEmeraldTablet/simple-agent-search-cron-task"
